### ISSUE TITLE
`Template` struct doesn't derive common traits

### ISSUE THREAD

**Issue by ironhouzi** [hasezoey/new_string_template#3]
I'm missing `Debug`, but not having `Clone` is crucial to me.

Is there a good reason for not deriving these?

**Comment by hasezoey** [comment]
> Is there a good reason for not deriving these?

no reason, just didnt need it yet (forgot to do it)

will address in next update

**Comment by ironhouzi** [comment]
I see. Will you be having a feature branch for this, which I can use while waiting for a stable release? If not, I'll try and fork locally in the mean time. I wouldn't mind contributing, but I'm a true novice Rust dev, so I'd be worried that I wouldn't be using the right idioms or methodology.

**Comment by hasezoey** [comment]
> which I can use while waiting for a stable release?

i dont really delay stable releases (this is not a big project), so it should be out in at least 5min or at most 4 hours
